### ISSUE TITLE
Non consumable products get consumed

### ISSUE THREAD

**Issue by davidmartos96** [RevenueCat/purchases-android#139]
_This is taken from the [discuss forum](https://docs.revenuecat.com/discuss/5eaee0cdf72c0d00528cb922), but I think it may be more appropriate to post it here_

Hi! I am exploring RevenueCat as an alternative for handling purchases and subscriptions in my app on Android.

At the moment I am using the queryPurchases method to restore non consumable products, and it works great upon app reinstallations. But after replacing my current implementation with RevenueCat I noticed that the non consumable products get consumed after they are synced in the Dashboard.

Is the consumption necessary? Wouldn't that make the purchase unobtainable if in the future I stop using RC?
I don't use a backend and all the users are anonymous, so I am relying on the non consumable products being available.

I am aware that exists a method called restorePurchases which calls queryPurchaseHistoyAsync under the hood. But I have read that with the new billing API is recommended to just call queryPurchases, which returns active purchases (No refunded or canceled products).

These are questions I have come up with while exploring RC. It really is a great service. Thank you

**Comment by rkotzy** [comment]
Android doesn't have a concept of "non-consumable" products like Apple does, RevenueCat can't intelligently consume or not consume certain products with the current setup - all non-subscription products are treated the same. Since the purchases are stored server-side, and can be restored by the user, it shouldn't pose too much of an issue. If you set a non-subscription product to unlock an Entitlement in RevenueCat, it can be used to give the user lifetime access to some feature.

In the future, we could add a configuration setting at the product level within the RevenueCat dashboard so we would know whether you want the product consumed or not. Adding this as a client-side param could be error prone in failure cases and if purchases are initiated from outside of the app.

If you planned to move away from RevenueCat, you'd have to implement some restore functionality for existing users, and we'd happily export all the purchase tokens we have saved for your users if that would help.

**Comment by davidmartos96** [comment]
Thanks for the answer. The issue was more like a question on why are they consumed in the first place. Is it because there is no way to distinguish the consumable and the non consumable products in the Billing Client library?
I think it would be great to include some notice in the documentation about this behavior. Because when testing the plugin, it may cause confusion that the purchase is not there anymore if requesting it with queryPurchases. When trying it my self it seemed weird that after installing my app with RC and then going back to a different version without RC, the non consumable purchases were not showing up.

**Comment by aboedo** [comment]
This is a valid concern. 

As @rkotzy mentioned, as of right now if your app does not have a backend and you want to move away from RevenueCat, you could implement restore functionality for existing users, and we might add backend-side configuration so that the SDKs can selectively consume IAPs. 

I also think @davidmartos96's suggestion of adding something to the docs is a great idea. We'll make them clearer. 

I'm closing this issue for now, since it's a feature request and we've made our product team aware of it, and we reserve GitHub Issues for bug reports. Feel free to follow up with [RevenueCat Support](support.revenuecat.com) if you need further assistance.

**Comment by ubuntudroid** [comment]
@aboedo Sorry for posting on this closed issue again, but I'm confused. I reread all your comments and from @rkotzy 's last post it sounds like your backend is doing the consuming (though I might read that wrong):

> In the future, we could add a configuration setting at the product level within the RevenueCat dashboard so we would know whether you want the product consumed or not. Adding this as a client-side param could be error prone in failure cases and if purchases are initiated from outside of the app.

Looking at the SDK code it's certainly the client (`Purchases.consumeAndSave()`) which does the consuming - which actually makes sense as I am not aware of a REST API to consume purchases (there only is one for acknowledging).

There is the `finishTransactions` flag which apparently can be set to `false` to prevent consumption from happening, however it then also prevents acknowledgment of subscriptions which in most cases wouldn't be what you want.

So it appears to me that the first step of the implementation is quite straight-forward here: Just split up the `finishTransactions` flag into two distinct flags: `acknowledgePurchases` and `consumePurchases`. This would likely already fix the problem for most developers with the lifetime package use-case.

To improve on that, one could later implement a feature that would allow to define the consume flag on a product level in the RevenueCat dashboard which would then be sent along to the clients which in turn would consume or not after purchase based on the product's consume flag.

Would step 1 be something which could be implemented reasonably quickly? I'd be happy to beta test and/or aid with implementation. :)

**Comment by aboedo** [comment]
@ubuntudroid that's correct, consumption happens purely SDK-side. 
The thinking around the backend was so that users could define it from the dashboard on a per-product basis, and so that it could even be done at runtime, for flexibility. 
The backend would then inform the SDK of whether it needs to consume the purchase or not. 

I like the idea of splitting `finishTransactions` into `acknowledgePurchases` and `consumePurchases`. The implementation isn't trivial because `finishTransactions` is very closely tied with observer mode, but I agree that it might be a good alternative first step. 
//cc @rkotzy @vegaro

**Comment by gaodeng** [comment]
any news?

**Comment by gaodeng** [comment]
any news?

**Comment by Maradox** [comment]
Could you please provide an update for this issue? The only workaround is to use observer-mode but then the app has to implement billing on its own for purchasing.
