### ISSUE TITLE
Memory leak in applicationContext

### ISSUE THREAD

**Issue by szeidner** [RevenueCat/purchases-android#153]
LeakCanary detects a leak in Purchases where the applicationContext is held onto when the app is backgrounded. Library version 3.1.1 and Android billing 2.2.1

![Screenshot_1591379576](https://user-images.githubusercontent.com/333099/83907995-55edb080-a734-11ea-9877-b029d2054d6f.png)

**Comment by vegaro** [comment]
Are you passing the MainActivity context to Purchases when calling configure?

**Comment by szeidner** [comment]
Ah you are absolutely right, I thought I was passing the application context, but it was actually the MainActivity context 🤦

**Comment by vegaro** [comment]
Glad to hear it's just that! There is actually a bug in the latest version that would hold to whatever context is passed to configure, instead of holding the applicationContext (even though the property is called Purchases.applicationContext 🤦‍♂️ ). We merged a PR this week https://github.com/RevenueCat/purchases-android/pull/147 that should fix it and avoid problems like what you were facing 😄
