### ISSUE TITLE
There is no singleton instance. Make sure you configure Purchases before trying to get the default instance.

### ISSUE THREAD

**Issue by limamauricio** [RevenueCat/purchases-android#198]
I call Purchases.configure(this, "api_key"); in my splash screen, but in Store Activity I get this error sometimes.

Unable to start activity ComponentInfo: There is no singleton instance. Make sure you configure Purchases before trying to get the default instance.

![Captura de tela de 2020-10-01 13-47-23](https://user-images.githubusercontent.com/4194664/94838941-b17f3080-03ec-11eb-94c5-5dd92e4817d3.png)

**Comment by vegaro** [comment]
Hi @limamauricio

Is it possible that the Store Activity runs before the Splash Screen?

I would recommend you to configure the SDK in your Application class instead of in the Splash Screen.

**Comment by limamauricio** [comment]
Well, the splash screen is the application launch screen. Store Activity should not run before splash screen, but it is possible in the android app life cycle. Is there any method to check if a singleton instance exists?

**Comment by rkotzy** [comment]
There isn't a method in the SDK to check if a singleton instance already exists. Going to close this out since it doesn't appear to be an Android SDK issue. 

Feel free to get in touch with the RevenueCat support team through the [Help Center](https://support.revenuecat.com/hc/en-us) or Stackoverflow if it's code specific to your app.
