### ISSUE TITLE
Are you open for contributors?

### ISSUE THREAD

**Issue by herou** [RevenueCat/purchases-android#227]
I like this product and I would like to contribute.  Do you have any easy issue to start on?

**Comment by taquitos** [comment]
Hey @herou, thank you for your patience 😄 We're actively working on how we can share feature development, bug fixing, and even roadmaps in order to make accept contributions from folks like you something we can do! We want to get this right, so it's taking a little bit of time (we're only just a few developers 🔧 on the SDK side ), but we hope you're enjoying using RevenueCat in the meantime!

**Comment by taquitos** [comment]
We're going to move issues from our internal tracking tool out here.

**Comment by taquitos** [comment]
Still working on the best way to surface our work in GitHub and help folks like you find fun things to contribute! I'm going to close this for now. I've made note of it and we'll prioritize sharing more in the future [CSDK-356].
