### ISSUE TITLE
Crashes during Purchases initialization through Purchases.configure()

### ISSUE THREAD

**Issue by Thib75** [RevenueCat/purchases-android#240]
Hi 👋

I am experiencing some issues during the initialization of the `Purchases` object when calling `Purchases.configure(context, key, userID)`.

Our users are under the following environment:
- Platform: android
- SDK version: 4.0.0
- Android OS version: 8, 9, 10
- Android Studio version: 4.1.1

Unfortunately, we could not reproduce these issues, but to give more context, we have a SplashScreen activity that inits the Purchases object through the configure method. The context is not null, the key is not null as well, and the userID can be null sometimes. The issue seems to be related to the `Lifecycle's observers list` of the `ProcessLifecycleOwner` object.

We have 3 types of crashes appearing:

- NullPointerException
<img width="1262" alt="null" src="https://user-images.githubusercontent.com/11028084/103669173-4f4c4380-4f78-11eb-8dcc-f27380ea9dea.png">

- IndexOutOfBoundsException
<img width="1268" alt="outOfBounds" src="https://user-images.githubusercontent.com/11028084/103669334-83bfff80-4f78-11eb-843e-4bfd44dc46af.png">

- ArrayIndexOutOfBoundsException
<img width="1272" alt="indexOutOfBounds" src="https://user-images.githubusercontent.com/11028084/103669445-a2be9180-4f78-11eb-8714-76aa96d10724.png">

I remain at your disposal for any further details you might want to discuss 😊

Thanks for your help!

**Comment by vegaro** [comment]
These crashes look similar to https://github.com/RevenueCat/react-native-purchases/issues/184

I have been holding on updating the lifecycle library because it was still on a pre-release stage, but I see they released a release candidate `Version 2.3.0-rc01` already, so I am going to update it and make sure we call `addObserver` and `removeObserver` from the Main thread so we can close these issues (hopefully).

On the meantime, I think if you can guarantee you are calling `Purchases.configure` from the Main thread, you could see those crashes disappear. Let us know if they don't.

**Comment by Thib75** [comment]
Hi @vegaro 👋

Thanks for your answer, I will follow your recommendations about the main thread, and keep you in touch about it 👍

Thank you 😊

**Comment by vegaro** [comment]
I have merged the PR that updates the version and makes sure we call those functions from the main thread. It will go out in the next release. Feel free to reopen it if you're still seeing it.

Thanks!!
