### ISSUE TITLE
Purchases.sharedInstance.purchase(...) should not require an Activity to be passed through

### ISSUE THREAD

**Issue by tomtaila-wesayhi** [RevenueCat/purchases-android#330]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

Separation of layers is difficult to achieve when the data layer (which is where Purchases.sharedInstance.purchase()) requires an Activity (which is a presentation layer entity) to be passed through. 
Doing so breaks clean architecture so could this please be changed?

**Comment by vegaro** [comment]
Hi @tomtaila-wesayhi ! The reason why we require an Activity is because the BillingClient itself requires an Activity to launch the billing flow https://developer.android.com/reference/com/android/billingclient/api/BillingClient#launchBillingFlow(android.app.Activity,%20com.android.billingclient.api.BillingFlowParams). We call `launchBillingFlow` internally and there's no other way to start a new purchase in Android so I am sorry to say that we can't change that 😞
