### ISSUE TITLE
One signal integration doesn't work - webhook response error 400

### ISSUE THREAD

**Issue by davidcz95** [RevenueCat/purchases-android#346]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

Hello,

I have a problem because I tried to integrate onesignal with revenuecat, and followed OneSignal integration guide, userid is set correctly but when the purchase is made or renewed webhook of onesignal is in “Retrying” status forever. And it gives response error 400 and this is the output:

{
  "CF-Cache-Status": "DYNAMIC",
  "CF-RAY": "67a058b2ad045d8b-IAD",
  "Connection": "keep-alive",
  "Content-Length": "41",
  "Content-Type": "application/json",
  "Date": "Thu, 05 Aug 2021 13:24:34 GMT",
  "Expect-CT": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "Server": "cloudflare",
  "access-control-allow-origin": "*",
  "alt-svc": "h3-27=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3=\":443\"; ma=86400"
}

This is the HEADER, the body is empty.

I will be grateful for any sugestions.

**Comment by aboedo** [comment]
hi @davidcz95!! 👋 
I believe you posted this question [to the community as well](https://community.revenuecat.com/third-party-integrations-53/one-signal-integration-doesn-t-worki-webhook-response-error-400-244), let's keep the conversation unified there. 

We reserve GitHub issues for SDK bug reports only, so I'm going to close this issue out since it looks like a configuration issue with the OneSignal integration, but we'll help you figure it out through the Community!
