### ISSUE TITLE
Purchase SDK: Subscription Dialog disappears when app is in the background

### ISSUE THREAD

**Issue by DarrylBaylissAtTheBodyCoach** [RevenueCat/purchases-android#510]
- [ ] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
When calling `purchases.purchasePackageWith(activity, packageToPurchase, onError, onSuccess)`, the Google subscription dialog is shown to confirm the subscription and the choice of payment method.

Ocassionally, the payment method requires authorization via the users payment app. This requires the user to background the app to confirm the authorization. When the authorization is confirmed and the user goes back to the app, the subscription dialog has disappeared. Note this doesn't always happen.

We believe it's due to Android cleaning up memory. For us, it means users cannot progress past the subscription screen. I appreciate this may not be an issue related to the RevenuecAT SDK directly and more the Google BillingClient, it's a behaviour that causes frustration for our users.

Our attempt to fix this is to create a foreground service to ensure the app isn't killed by the OS. It would be better if RevenueCat could do this or provide another suitable workaround.

1. Environment
   1. Platform: Android
   2. SDK version: 4.6.0
   3. OS version: 12
   4. Android Studio version: BumbleBee 2021.1.1
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

N/A

4. Steps to reproduce, with a description of expected vs. actual behavior

- Call purchases.purchasePackageWith(activity, packageToPurchase, onError, onSuccess) with a valid package setup
- When the google subscription dialog appears, select a payment method and continue
- If the subscription dialog asked to authorize payment, exit the app to perform the authorization
- Go back to the app after authorization is confirmed, observe the subscription dialog has disappeared

5. **Other information** 

N/A

**Additional context**

N/A

**Comment by beylmk** [comment]
Hey @DarrylBaylissAtTheBodyCoach, thanks for opening an issue, and for a potential solution :) I'll try to reproduce today and think through whether we can provide this fix on the RevenueCat side...

**Comment by beylmk** [comment]
Hey @DarrylBaylissAtTheBodyCoach, I'm having trouble reproducing. I haven't found any way to force the payment authorization dialog, and the subscription dialog remains for me when backgrounding otherwise. Were you able to reproduce in debug, or do you have more info on what kinds of scenarios lead to the payment authorization request?

**Comment by DarrylBaylissAtTheBodyCoach** [comment]
Hey @beylmk,

Sorry to hear you're having trouble reproducing. It's a tricky one as the payment authorisation dialog only appears in a production build when the users bank / payment method requests authorisation.

Our solution for testing is to publish a Google Play app build using a test track so the Google BillingClient can access their backend. It's not 100% realistic as it's a test environment but we see the issue where the dialog disappears here as well. 

Note the authorisation step for google billing doesn't occur when publishing to a test track. We just background the app when the google subscription dialog appears, sometimes opening other apps and then going back to the app with the subscription dialog can force the behaviour we see.

I hope that helps!

**Comment by beylmk** [comment]
Hey @DarrylBaylissAtTheBodyCoach, I'm unfortunately still unable to reproduce in an alpha test.

Thinking through what could be going on here... I'm wondering if perhaps it's okay that the dialog is gone, as long as the purchase still completes. Have you implemented an [UpdatedCustomerInfoListener](https://github.com/RevenueCat/purchases-android/blob/main/purchases/src/main/java/com/revenuecat/purchases/interfaces/UpdatedCustomerInfoListener.java) (previously `UpdatedPurchaserInfoListener` until our 5.0.0 release yesterday...)? If the purchase went through, the next time the app foregrounds we'd query for purchases and send an updated `CustomerInfo` to the listener.

If you're able to tell whether the purchase completes, that'd be helpful.

I'm also not sure whether a ForegroundService would solve this problem...did it work for you? I think that'd keep the _app_ alive, but not necessarily Google's dialog. 

I wish I could reproduce this so that I can better understand how the payment authorization flow works, but I haven't found anything online about how to force it.

**Comment by DarrylBaylissAtTheBodyCoach** [comment]
Hey @beylmk,

We're almost at the point where we're ready to test our solution with a willing customer. I can keep you updated on that if its helpful?

I don't think `UpdatedCustomerInfoListener` would help in this instance, as the purchase does not complete the Google subscription dialog flow. My assumption is even if we did inform RevenueCat, Google Play would report the purchase didn't happen. Perhaps I am missing something however.

Our users who report this don't appear to have completed the purchase, as they don't progress past the subscription screen. Again, I could be missing something.
