### ISSUE TITLE
Flag isActive still true even cancel subscription from Google Play Store

### ISSUE THREAD

**Issue by thanhduy26091995** [RevenueCat/purchases-android#565]
- [ x] I have updated Purchases SDK to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x ] I have searched the [Community](https://community.revenuecat.com)
- [x ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: Android
   2. SDK version: 31
   3. OS version: 11
   4. Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 3
   5. How widespread is the issue. Percentage of devices affected.: 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

I'm migrating with new RevenueCat SDK (5.1.1) 
I'm facing an issue that after cancel subscription from Google Play Store, and the subscription already expire, but I still receive flag isActive = true, with expiration date is in the past

This issue not happen with RevenueCat SDK (4.3.0)
Both SDK using sandbox

Also, I'm looking into your SDK, and found that ProcessLifecycleOwner.get().lifecycle.addObserver(lifecycleHandler) will not call on function onAppBackgrounded and onAppForegrounded , it already deprecate and should be updated

**Comment by vegaro** [comment]
@thanhduy26091995 first of all, thanks for pointing that out about ProcessLifecycle observer, we'll get that updated.

Regarding `isActive`. This is the logic we use to determine if the entitlement is active:

```
        isActive = expirationDate == null || expirationDate.after(requestDate ?: Date()),
```

You will notice that we are comparing against `expirationDate` against `requestDate` and not always against today's date. The reason for this comparison is that we cache the `CustomerInfo` and we check if the entitlement was active at the moment when it was cached. If we were to always compare against today's date and the app couldn't update the CustomerInfo because it can't communicate with our servers (let's say the phone is in airplane mode) the user would lose access even if they have renewed the subscription. We take an optimistic approach and assume the user renews, because we think it's a better experience to provide access to the entitlement even if they haven't renewed than to remove the access to someone that has actually renewed it. 

We have a caching policy of 5 minutes, so it's possible that what you are seeing is the `isActive` of a cached `CustomerInfo`. 5 minutes can seem pretty long for a subscription in a sandbox environment, since a monthly subscription renews every 5 minutes.

Most apps don't even work without internet, so the fact that we might grant access after expiration is not really a big issue because since the app most likely won't work without internet. In any case, if you prefer a different behavior, we just released version 5.2.0 of our SDK, which adds a new API that lets you customize the cache policy when calling `getCustomerInfo`. [This is the PR](https://github.com/RevenueCat/purchases-android/pull/546/files#diff-e019410c58657f001e6ba8be4f066c84c928f4e017ae3b3b6366cebfd64b9716R631) that added it and this is the function [code](https://github.com/RevenueCat/purchases-android/blob/main/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L637) and the [docs for it](https://sdk.revenuecat.com/android/5.2.0/purchases/com.revenuecat.purchases/-purchases/get-customer-info.html).

Let me know if that's clear.

**Comment by thanhduy26091995** [comment]
hi @vegaro 

Thanks for your replying.
I understood your scenario

I tried version 5.2.0 with cachingPolicy. So every time open app, I force SDK call from network (CacheFetchPolicy.FETCH_CURRENT), and it's working fine.

But if I don't use force update (CacheFetchPolicy.FETCH_CURRENT), I found that isActive is still flag to true
I checked CustomerInfo object, field "`expiresDate`" is `Fri Jul 15 15:08:14 GMT+07:00 2022`, but now is `Sat Jul 16 10:45 GMT+7 2022` as a time I debug, flag isActive should be **false**, but it still **true**

Here is full response of CustomerInfo

> <CustomerInfo
 latestExpirationDate: Fri Jul 15 15:08:14 GMT+07:00 2022
activeSubscriptions:  {com.zyncas.signals.weekly={expiresDate=Fri Jul 15 15:08:14 GMT+07:00 2022}},
activeEntitlements: [premium=EntitlementInfo(identifier='premium', isActive=true, willRenew=true, periodType=NORMAL, latestPurchaseDate=Fri Jul 15 15:01:17 GMT+07:00 2022, originalPurchaseDate=Fri Jul 15 15:01:17 GMT+07:00 2022, expirationDate=Fri Jul 15 15:08:14 GMT+07:00 2022, store=PLAY_STORE, productIdentifier='com.zyncas.signals.weekly', isSandbox=true, unsubscribeDetectedAt=null, billingIssueDetectedAt=null, ownershipType=UNKNOWN)],
entitlements: [premium=EntitlementInfo(identifier='premium', isActive=true, willRenew=true, periodType=NORMAL, latestPurchaseDate=Fri Jul 15 15:01:17 GMT+07:00 2022, originalPurchaseDate=Fri Jul 15 15:01:17 GMT+07:00 2022, expirationDate=Fri Jul 15 15:08:14 GMT+07:00 2022, store=PLAY_STORE, productIdentifier='com.zyncas.signals.weekly', isSandbox=true, unsubscribeDetectedAt=null, billingIssueDetectedAt=null, ownershipType=UNKNOWN)],
nonSubscriptionTransactions: [],
requestDate: Fri Jul 15 15:01:24 GMT+07:00 2022
>

So does it affect to production env? Noted that I'm trying with Sandbox.

Thanks

**Comment by vegaro** [comment]
If you don't force update the purchaser info in production it's possible that your users open the app and use a cached customer info that shows they are premium because it's an old customer info that was fetched when the subscription was still active (that's what you're seeing in the response you sent). That customer info will be tried to be updated (if the cache is older than 5 minutes) when the app is foregrounded and during configuration of the SDK, and if the subscription has expired the `isActive` property will be changed to `false`. We will send the updated customer info to the `UpdatedCustomerInfoListener` which we recommend to use to listen to changes in the CustomerInfo https://docs.revenuecat.com/docs/configuring-sdk#android. Have you configured the `UpdatedCustomerInfoListener` listener?

**Comment by duybuikardiachain** [comment]
That customer info will be tried to be updated (if the cache is older than 5 minutes) when the app is foregrounded and during configuration of the SDK => I tried to put app in foreground over 5 mins, tried close app and open again, flag `isActive` still true event it's already expired. Noted that, this case I'm not force get purchased info from server

Have you configured the UpdatedCustomerInfoListener listener? => Yes, I already handle this interface, If I force, I will receive a response from this callback

Did you reach this issue on your side? 

**`Noted: For clarify, if I use this flag  CacheFetchPolicy.FETCH_CURRENT, the flow is OK, just curious about behavior without force`**

**Comment by thanhduy26091995** [comment]
That customer info will be tried to be updated (if the cache is older than 5 minutes) when the app is foregrounded and during configuration of the SDK => I tried to put app in foreground over 5 mins, tried close app and open again, flag `isActive` still true event it's already expired. Noted that, this case I'm not force get purchased info from server

Have you configured the UpdatedCustomerInfoListener listener? => Yes, I already handle this interface, If I force, I will receive a response from this callback

Did you reach this issue on your side?

**`Noted: For clarify, if I use this flag CacheFetchPolicy.FETCH_CURRENT, the flow is OK, just curious about behavior without force`**

**Comment by beylmk** [comment]
`Yes, I already handle this interface, If I force, I will receive a response from this callback` -- what do you mean by "if I force?" Are you saying that this listener doesn't get an update at all when you don't set `FETCH_CURRENT`? 

With `CACHED_OR_FETCHED`, the default when you aren't setting `FETCH_CURRENT`, the getCustomerInfo function  ```returns the cached data if available (even if stale). If not available, fetches
     *  up-to-date data. If cached data is stale, it initiates a fetch in the background.```
So I think what's happening is that `getCustomerInfo` returns the cached CustomerInfo, with the `isActive` that is technically "incorrect". But then a fetch is happening in the background, which would update the listener AFTER you get the callback from getCustomerInfo. So the `UpdatedCustomerInfoListener` should have the correct `isActive` property. 

Let me know if this is unclear...in the meantime, I'll confirm that the `CustomerUpdateListener` in our sample app still gets an update without setting `FETCH_CURRENT`.

**Comment by beylmk** [comment]
@thanhduy26091995 I confirmed I don't see this in the sample app...if my explanation above doesn't explain what's happening for you, would you mind attaching some debug logs? You can enable them with `Purchases.debugLogsEnabled = true` before configuring.
